### ISSUE TITLE
Tab10 KEY.IV

### ISSUE THREAD

**Issue by 350886** [Hagb/decryptBooxUpdateUpx#100]
g6KR6v6fhLWc5HL8I1WS2GLX6uWFEkU8SBgrNMWhQC8m
C301F33490ABF2C9396E335D3258BD37

8tOTmY6dgrjDo0MV8GTL7tvlM4mOAU1l7P7nIRVVlOuO
2B2B6159E3CA418F71D58966310B764F

**Comment by RenateUSB** [comment]
Added to BooxKeys.csv
