### ISSUE TITLE
I got keys for Poke5S, and I want to get keys for Poke5Lite.

### ISSUE THREAD

**Issue by erehwonlab** [Hagb/decryptBooxUpdateUpx#101]
I'd like to submit unlisted keys for Poke5S. I'm happy to use this for anyone who need it.
I verified this myself.

```
"MODEL" = "Poke5S",
"STRING_SETTINGS" = "WpVdC3ZNsoNW+iwneydETT4SCuZnwgeoe1S+x1nxRK6C",
"STRING_UPGRADE" = "KOJcC3IxsPL6RL6daev1KqLC7ltFiUkjggmJiZ82nCFI"
# fingerprint: Onyx/Poke5S/Poke5S:[11/2024-03-08](tel:11/2024-03-08)_06-39_3.5.1_85dbbdf26/7953:user/dev-keys
```

by [BooxKeyConvert.py](https://github.com/Hagb/decryptBooxUpdateUpx/blob/master/BooxKeyConvert.py)

Poke5S,Poke5S,AE0FB835F4A50D35C95FEC7700EEDF1D,321FFD1D14E8A2A7A422C683D152AF3B

**Comment by RenateUSB** [comment]
Thank you! Added to BooxKeys.csv
