### ISSUE TITLE
Can someone get the key for Go103? I tried following the tutorial, but didn't succeed.

### ISSUE THREAD

**Issue by 0xEEEE** [Hagb/decryptBooxUpdateUpx#102]
[libota_jni.so.zip](https://github.com/user-attachments/files/16033994/libota_jni.so.zip)

Here is libota_jni.so.

Thank you.

**Comment by RenateUSB** [comment]
Say what? I just put the Go103 in 7 minutes ago.

**Comment by 0xEEEE** [comment]
> Say what? I just put the Go103 in 7 minutes ago.

Awesome LOL!
