### ISSUE TITLE
Please help me get the keys for KANT

### ISSUE THREAD

**Issue by zeroma25** [Hagb/decryptBooxUpdateUpx#103]
Model: KANT
[libota_jni.zip](https://github.com/user-attachments/files/16111067/libota_jni.zip)
[OnyxOtaService.zip](https://github.com/user-attachments/files/16111068/OnyxOtaService.zip)

**Comment by RenateUSB** [comment]
Key for KANT added, but the update link is giving 403 so not completely verified.
