### ISSUE TITLE
Key of FLOWPro

### ISSUE THREAD

**Issue by xljxlj** [Hagb/decryptBooxUpdateUpx#106]
FLOW.Pro

<string name="settings">ajqB7YXj9zQNYc/8r6NSaKrAdkT910WU5g8gD9mm6LcH</string>
714C5E4655170DA6774E7E1DFCF78D9E
<string name="upgrade">bTP0noOQ+kGVZiqrdMHG50pI2yjLedU7vIdL+f7ffiz+</string>
08A0369CAE896E52AF8694A2EF39C1EE

http://firmware.boox.com/971db33282c2a6620a6d5c5e0945fa08/update.upx

http://data.onyx-international.cn/api/firmware/update?where={"buildNumber":0,"buildType":"user","deviceMAC":"","lang":"zh_CN","model":"FLOWPro","submodel":"","fingerprint":""}

**Comment by RenateUSB** [comment]
Thank you! Added.
