### ISSUE TITLE
I got the libota_jni.so for T10C

### ISSUE THREAD

**Issue by WHC2006** [Hagb/decryptBooxUpdateUpx#110]
this is the file
https://drive.google.com/file/d/1VSRAq2G4zJ8EBIynn3Ufysv0FmCjp-0U/view?usp=drive_link

**Comment by WHC2006** [comment]
![image](https://github.com/user-attachments/assets/2cc913bb-b170-4058-9d21-758f0423d6e2)

**Comment by RenateUSB** [comment]
I got the keys, but what model are you talking about? We have Tab10C and Tab10CPro already. This is not either. Please specify exactly.
```
21B04F8458DCD400D6DD2FEDDF13BC16
C78066550FE7CE6CCAFB692FFFB0E3F5
```

**Comment by WHC2006** [comment]
![image](https://github.com/user-attachments/assets/4296a1b5-6b14-480e-82c7-8b60d252e782)
For the time being, the T10C is only available in China

**Comment by RenateUSB** [comment]
Ok, "T10C" it is. Added, thanks!

**Comment by RenateUSB** [comment]
Ok, "T10C" it is. Added, thanks!
