### ISSUE TITLE
Strings for Note

### ISSUE THREAD

**Issue by typingpanther** [Hagb/decryptBooxUpdateUpx#16]
[strings.xml.txt](https://github.com/Hagb/decryptBooxUpdateUpx/files/6660072/strings.xml.txt)

**Comment by typingpanther** [comment]
Also, if your tablet has the bootloader locked for whatever reason, this link shows you how to unlock it (data is wiped): http://opensource.rock-chips.com/wiki_Fastboot#Unlock_your_Device_via_Fastboot

**Comment by Hagb** [comment]
Thanks! The strings are verified and merged.
