### ISSUE TITLE
Can anyone help to get the string for Dedao Max( Note Air)?

### ISSUE THREAD

**Issue by James-Zhu-CA** [Hagb/decryptBooxUpdateUpx#17]
I am trying to flash the Dedao firmware to my Note air through the update menu, but it didn't allow. If I get the zip
file, maybe there is other way I can flash it in.

I get the file from here https://pan.baidu.com/s/18yacVkce64ecwOi6YA_LXw   code: f2UA

**Comment by James-Zhu-CA** [comment]
Or is it possible to modify the upx file to fake a note air version, maybe that also can pass the model verification.

**Comment by Hagb** [comment]
> I am trying to flash the Dedao firmware to my Note air through the update menu, but it didn't allow. If I get the zip
> file, maybe there is other way I can flash it in.
> 
> I get the file from here https://pan.baidu.com/s/18yacVkce64ecwOi6YA_LXw code: f2UA

As far as I know, to get the encryption key (called "strings" in this project), firstly a device with the firmware installed already is needed because there is not other way to get `OnyxOtaService.apk` for this firmware.

**Comment by RenateUSB** [comment]
This issue is very old. If you are still interested, please reissue it.
