### ISSUE TITLE
Please add the key for Poke Pro

### ISSUE THREAD

**Issue by RamDino** [Hagb/decryptBooxUpdateUpx#20]
Here's the key

'Poke_Pro': {
    "MODEL": "Poke_Pro",
    "STRING_SETTINGS": "6GxQ6Iei3y2PSf6Wlayz+0f6yVnl1GXe5OC3q3i2lasO",
    "STRING_UPGRADE": "72lZ7vTQoy9/ESDKRQtx2V5uBMDiR+ik3n+soo9wGAbJ",
    "STRING_LOCAL": "hkkAqdfM93RpnCgXxhUqzme3OMzT6tDWC3fyibgW"
}

**Comment by Hagb** [comment]
Thanks! They are verified and merged.
