### ISSUE TITLE
What's the string for Max 2 Pro?

### ISSUE THREAD

**Issue by yubrshen** [Hagb/decryptBooxUpdateUpx#21]
Really appreciate your help to confirm the string for Max 2 Pro.
By the pattern of the strings for the other models, it seems that it could be 
Max2Pro
?

**Comment by winstonma** [comment]
Indeed it is Max2Pro

http://data.onyx-international.cn/api/firmware/update?where={%22buildNumber%22:0,%22buildType%22:%22user%22,%22deviceMAC%22:%22%22,%22lang%22:%22en_US%22,%22model%22:%22Max2Pro%22,%22submodel%22:%22%22,%22fingerprint%22:%22%22}

**Comment by RenateUSB** [comment]
@Hagb Could you close this?
