### ISSUE TITLE
增加设备 SP_NoteS

### ISSUE THREAD

**Issue by taoHC1997** [Hagb/decryptBooxUpdateUpx#24]
我有一台 `超星Note SL` ，是 `note S` 的定制版

此版本使用： `http://data.onyx-international.cn/api/firmware/update?where={"buildNumber":0,"buildType":"user","deviceMAC":"","lang":"zh_CN","model":"SP_NoteS","submodel":"","fingerprint":""} `

下面是拆包得到的文件：

````
    'SP_NoteS': {
        "MODEL": "SP_NoteS",
        "STRING_SETTINGS": "XjzywnKKh3FNVKphg5MZ9xILmDNYBZiCHTnkd6Q0fqpq",
        "STRING_UPGRADE": "XDeIyQKAhQKj6/UmdAIWoL0aXmw9PeEFl9OpII/1TO9i",
        "STRING_LOCAL": "QmGqhFGXqiuQ9yoeVx0a2SQ8BNojjPn96o6hQW6U"
    },
````

**Comment by Hagb** [comment]
感谢！验证了一下确实无误，加到代码里了。
> Thanks! The strings are verified and merged.

**Comment by xif12jhj** [comment]
请问你的改完有电磁屏固件吗？

**Comment by RenateUSB** [comment]
> 请问你的改完有电磁屏固件吗？
> Do you have the electromagnetic shield firmware after you made the changes?

Sorry, I have no idea what you mean.
