### ISSUE TITLE
增加设备 `NoteS`

### ISSUE THREAD

**Issue by taoHC1997** [Hagb/decryptBooxUpdateUpx#25]
从[贴吧](https://tieba.baidu.com/p/7627028543)网友提供的 apk 解密得来：
更新网址： ` http://data.onyx-international.cn/api/firmware/update?where={"buildNumber":0,"buildType":"user","deviceMAC":"","lang":"zh_CN","model":"NoteS","submodel":"","fingerprint":""}` 
下面是拆包所得：
```
    'NoteS': {
        "MODEL": "NoteS",
        "STRING_SETTINGS": "+YKimeg208RzM8InqtuUjSIopyM2OLIMpFeeTQby2Au4",
        "STRING_UPGRADE": "+vap6p4w0MaT5A8RB4+ru3gnFtIq2g4K+tcjQjy3N599",
        "STRING_LOCAL": "5qT7388vj+/FwLMX/cIXSCgSxSIg9SAf0tB4NcEI"
    },
```

**Comment by Hagb** [comment]
感谢！验证无误，已合并。
> Thanks! The strings are verified and merged.
