### ISSUE TITLE
Strings for Leaf

### ISSUE THREAD

**Issue by shirleyggithub** [Hagb/decryptBooxUpdateUpx#26]
'Leaf': {
        "MODEL": "Leaf",
        "STRING_SETTINGS": "kh5V130fLNcO5lgsSDq7aUxQOz98DzEmiur3YsYKreIs",
        "STRING_UPGRADE": "kBtW135kW9zvvgRlsTolCktkJ7+MeW5ZoNgr3xyr2SpX",
        "STRING_LOCAL": "jzx1lloJdIBGjmcyS9oYPmXvTKFp4dpj66fPcaON"        
    },

**Comment by Hagb** [comment]
Thanks! The strings are verified and merged.
