### ISSUE TITLE
Looking for PadMu 3 Lumi strings

### ISSUE THREAD

**Issue by rdoursenaud** [Hagb/decryptBooxUpdateUpx#28]
Can anyone please provide PadMu 3 Lumi aka `PadMu3L` strings?

Thanks.

**Comment by RenateUSB** [comment]
This issue is very old. If you are still interested, please reissue it.

**Comment by rdoursenaud** [comment]
Yes, still very much interested.

**Comment by rdoursenaud** [comment]
I would if I had one.
Unfortunately I don't own this device, hence my request.
I do however have ".upx" update files I'd like to decrypt.

**Comment by RenateUSB** [comment]
I'm failing to grasp why you want to decrypt a two year old update for a device that you don't own.
In any case, there is nothing anybody can do for you.

**Comment by rdoursenaud** [comment]
Well, I was hoping for someone with a PadMu 3 Lumi device to be willing to share the strings to allow me to hack PadMu onto the otherwise identical Boox Max Lumi device I own since PadMu is unwilling to sell just its software.
I thought that having this issue open was the correct thing to do since it's missing from the repository and would incentivize an owner to participate.
Sorry if I was mistaken.

**Comment by RenateUSB** [comment]
Why not use the recent update for the MaxLumi?
```
Model:  MaxLumi
Finger: ONYX/MaxLumi/MaxLumi:10/2023-04-20_12-34_3.3.2_856e3b0d6/10278:user/dev-keys
Link:   http://firmware-us-volc.boox.com/b1f0b9d22070397a09a0b78db27c5273/update.upx
Size:   1793869370
MD5:    b1f0b9d22070397a09a0b78db27c5273
```
If you're still looking for PadMu3Lumi users, find them on some forum. Issues are for when something can be done.
