### ISSUE TITLE
Any way to decrypt OYX?

### ISSUE THREAD

**Issue by gschanuel** [Hagb/decryptBooxUpdateUpx#29]
Hello there!
I got android 9 for my Nova Pro from here 
https://docs.google.com/forms/d/e/1FAIpQLSe51X66bVc5aSkgWglMnYiBU7QbXwiZ4hXUwgZo-kiZUyDtsA/viewform?fbclid=IwAR2UUMCvbL7saS0FtogoFRcAdPenPF2QncE_JgsjZ8U8eB_TmwXDWBIFVZ4
(need to answer the form to access the files)
Direct link here https://drive.google.com/drive/folders/1HcFjETKBJ6cJighGvpM9aDeHSU2e6fC0?usp=sharing

The file is not update.upx but uptade.oyx

Is there a way to decrypt this file too?

Thanks in advance

**Comment by gschanuel** [comment]
I don't believe it was that simple!! :-)
It worked
thanks!

**Comment by astroHaoPeng** [comment]
Amazing. Just to confirm that this password `oNyxEnc8686` also works for the Note Pro's `update.oyx`. 
BTW, can you share more insights on how you get this password?
