### ISSUE TITLE
Strings for Note2

### ISSUE THREAD

**Issue by nono2357** [Hagb/decryptBooxUpdateUpx#3]
Model: Note2
"STRING_7F00500": "etwiPPEXAQRj3m+e0Q2FOxT16aJ8XexQAqhGn5NqZWv1"
"STRING_7F00501": "et0jSPpmd3ueGHLmMf+2yyXVn18sa2HrDg56dCTFH6lf"
"STRING_7F00502": "YY9wfqN7K1LlSug47Tr5Y8QkDHmmJ4VDCJ58mhoV"

Thanks for the tool!

**Comment by Hagb** [comment]
Thanks for your string!
Verified and added to README.
