### ISSUE TITLE
Strings for livingstone-ru

### ISSUE THREAD

**Issue by syleront** [Hagb/decryptBooxUpdateUpx#34]
Got strings for livingstone (russian version)
|  MODEL  | SETTINGS  | UPGRADE  | LOCAL  |
|---|---|---|---|
| LIVINGSTONE  | ES5zbiHTesxFb+zdkjxiqJ+1dOwyOCv2BzCV7fOYDJxf  | EFwGaFSherxX1k6Hl/U6TiQhGJOzTPDfsPzHg+z9guln  | fQ5TLnfKUOHq0f7XXdu9b1FGAckqI576ZBPkZfPg  |

Proof below :)

![image](https://user-images.githubusercontent.com/17946851/177653316-e8fd65bd-de66-46d2-9b93-bd553de50a45.png)

**Comment by Hagb** [comment]
Thanks for your strings! Merged.
