### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by adam-kulagowski** [Hagb/decryptBooxUpdateUpx#37]
I'm not sure if all Onyx boox FW are like this, but inside Poke 4 Lite there was a single payload.bin which was a surprise for me. Could You add in Readme.md, an information that we can extract images from that file using tools from the following repo:

https://github.com/cyxx/extract_android_ota_payload

It would make life much easier for all new users.

**Comment by Hagb** [comment]
Thanks for your idea! The document has been updated.

**Comment by Hagb** [comment]
AFAIK, there are a few boox FW using `payload.bin`. The information should be useful.
