### ISSUE TITLE
[question] Can it be used to modify the Android OS on our device?

### ISSUE THREAD

**Issue by gustavklopp** [Hagb/decryptBooxUpdateUpx#41]
Great tool, thank you!
I'd like to have some precisions about the way we can use this tool:
Can it be use to modify the Android OS which is running on our device? 
Even further, what I'd like to do is to modify it to produce a LineageOS version (it's a community-produced Android) from the Android running on the device?
Thanks a lot in advance

**Comment by 1over137** [comment]
Anyone knows how to remove the "Store" tab?
I just want to have a e-ink android device without spyware and stores.

**Comment by RenateUSB** [comment]
Modifications to the system are not really the subject here. Look into using Magisk to modify your system.
