### ISSUE TITLE
Strings for Tab8

### ISSUE THREAD

**Issue by shirleyggithub** [Hagb/decryptBooxUpdateUpx#45]
'Tab8': {
        "MODEL": "Tab8",
        "STRING_SETTINGS": "Yjr0qRHMwEvCt4U3K5QtAVT97968eeMOFF2zx6f6ctFg",
        "STRING_UPGRADE": "E0+HqBG5s0Z9WT+eKt0oTL2BucEMDdsaElDGQQFOV9uF"
    },

**Comment by Hagb** [comment]
Thanks for your strings! They have been verified and merged.
