### ISSUE TITLE
Strings for Poke2

### ISSUE THREAD

**Issue by xavig33** [Hagb/decryptBooxUpdateUpx#48]
'Poke2': {
        "MODEL": "Poke2",
        "STRING_SETTINGS": "Lu3Xbc5vobO/8sveD6qjO/LEYeqd199myw3pybHynUEO",
        "STRING_UPGRADE": "WOqqHbls0bZ67ofyutQ+XG37zR09inkP+4G3Z/t9e7m6",
        "STRING_LOCAL": "QrzzLZp3/uz4MwBzb6SJ040+l8AshzAz1t/rG8B/"
    }

**Comment by Hagb** [comment]
Thanks for your strings! They have been verified and merged in 27e0cd7.
