### ISSUE TITLE
Strings for Leaf 2

### ISSUE THREAD

**Issue by baqlias** [Hagb/decryptBooxUpdateUpx#49]
"MODEL" = Leaf2",
"STRING_SETTINGS" = "okRZqgfOHft/Y5jHx1N0ECjqrc/Op/nADFj2uL7Jbuxq",
"STRING_UPGRADE" = "10Na33u5HfsCVHqjtwLrwACOW+2cz5MSnXUogONCTd9c"
# fingerprint: Onyx/Leaf2/Leaf2:11/2022-10-29_19-11_3.3.1_8c9d49397/1583:user/dev-keys

If there's anything missing, please let me know!

**Comment by CrazyCoder** [comment]
Duplicates https://github.com/Hagb/decryptBooxUpdateUpx/pull/46 :)

**Comment by Hagb** [comment]
Thanks for submitting the strings (though duplicates #46). Close for #46 is merged.
