### ISSUE TITLE
Strings for Onyx/FLOW (得到阅读器FLOW)

### ISSUE THREAD

**Issue by htchennuo1** [Hagb/decryptBooxUpdateUpx#51]
'FLOW': {
        "MODEL": "FLOW",
        "STRING_SETTINGS": "tzct2Ic6HFZzobeHcxxJ/EVt9EKMUZcaGHMN/uHZjEYW",
        "STRING_UPGRADE": "ukZbqPE8FiTbM2U12bfY4v0Xhwioj9zdKb5R2RuGL6/i",
        "STRING_LOCAL": "rGEKmqMjSX3+VMxtZNdDHF/ectjjqKIRuDMu5Mn2"
    }

**Comment by htchennuo1** [comment]
Firmware information:
{"_id":"6109f307a6b8c8726601ed92","updatedAt":"2021-08-09T06:14:46.342Z","createdAt":"2021-08-04T01:53:11.945Z","md5":"e5c145157f94bac91ebc9a82dac2d2bf","model":"FLOW","submodel":"","brand":"Onyx","fingerprint":"Onyx/FLOW/FLOW:9/2021-08-03_21-17_3.0.1_94be9d3/2910:user/dev-keys","buildType":"user","buildNumber":2910,"buildDisplayId":"2021-08-03_21-17_3.0.1_94be9d3","excludeGroups":false,"parentFingerprint":"","force":false,"__v":0,"availableCount":0,"whitelistMAC":[],"size":1485723270,"betaGroups":[],"downloadUrlList":["http://firmware-volc.boox.com/e5c145157f94bac91ebc9a82dac2d2bf/update.upx"],"changeList":["1.优化电子书阅读进度同步逻辑","2.优化电子书翻页体验","3.修复其他已知bug"],"fwType":"release"}

**Comment by htchennuo1** [comment]
Firmware Link: http://firmware-volc.boox.com/e5c145157f94bac91ebc9a82dac2d2bf/update.upx

**Comment by Hagb** [comment]
Thanks for your strings! They have been verified and merged in 7803c4d.
