### ISSUE TITLE
once we get the full upx zip file, can we use this to downgrade device ? 

### ISSUE THREAD

**Issue by alzuobaba** [Hagb/decryptBooxUpdateUpx#53]
since, my onyx note3 upgrade to 3.3.1, it always stucks

**Comment by Sollovin** [comment]
Maybe you can try flash some key partition images in the upx zip file with fastboot.

**Comment by tianjj11** [comment]
I use this code decryped Nova pro firmware success, Thank you very much!

**Comment by RenateUSB** [comment]
You could also just do a manual update in recovery.
You may have to edit updater-script in the zip to remove the anti-rollback line in the script.

**Comment by RenateUSB** [comment]
Modifications to the system are not really the subject here. Look into using Magisk to modify your system.
