### ISSUE TITLE
NoteAir3C, Poke5P, Tab10CPro, TabUltra strings

### ISSUE THREAD

**Issue by RenateUSB** [Hagb/decryptBooxUpdateUpx#62]
```
    'NoteAir3C': {
        'MODEL': 'NoteAir3C',
        'STRING_SETTINGS': 'MYW5k0CzVxi0BEFeifp7MA5Vpf/EdkmR1fQgsmG6E0Zz',
        'STRING_UPGRADE': 'PPfIlz3PVWigEgTadT2TpwjjzoDmxGkXcSTIql3320WO'
    },
    'Poke5P': {
        'MODEL': 'Poke5P',
        'STRING_SETTINGS': 'qxgpoanZIjVbMsdvYPNSHm8fjAUAHAqPrks0FAJxS4rB',
        'STRING_UPGRADE': 'rBtaoN3bUjFzHjHr7I3akO+0Z83BOl7Ts3JrJtbWNryO'
    },
    'Tab10CPro': {
        'MODEL': 'Tab10CPro',
        'STRING_SETTINGS': 'on8l4AwDwIgVNi6AgrAqLzkc94XMx9O37CCELz23Fm+J',
        'STRING_UPGRADE': 'pQIr4QYOsvxLqxXik9cIIzca+QzC2pa9U/hY8p/EAkur'
    },
    'TabUltra': {
        'MODEL': 'TabUltra',
        'STRING_SETTINGS': 'zsb+9c4SzqrAnPkdtIaoKcw4r5gjLr+anKJDYlypaMR+',
        'STRING_UPGRADE': 'yrX2h8weyduHDTK+oWbibAXbqBjGbDyEjeDb1pRRmkIl'
    },
```

(Of course the Tab10CPro and NoteAir3C don't actually have "strings" but these generates the correct key, iv.)
Please, can you just keep these in alphabetical order? It saves searching.
Also, consistent single quotes would be cool.

**Comment by usb9245** [comment]
```python3
'Poke5': {
    "MODEL": "Poke5",
    "STRING_SETTINGS": "WUg6pwei2Auz1Bt3KTw/VvYzYLyahqYmoRrp0CNDpQgw",
    "STRING_UPGRADE": "WDI+rnel2ni3FyHk8KtD/2NZcHit0b0ptb4k+QqAieKw"
}
```

for Poke5

**Comment by RenateUSB** [comment]
What is the difference between a Poke5 and a Poke5P?
I bought what was advertised as "Poke5", but the model and fingerprint show "Poke5P".
I've also not seen any updates for the "Poke5"

Also, Python is not JSON, we can just use single quotes everywhere.

**Comment by usb9245** [comment]
I think "Poke5" is chinese version of Poke5.
http://data.onyx-international.cn/api/firmware/update?where={%22buildNumber%22:0,%22buildType%22:%22user%22,%22deviceMAC%22:%22%22,%22lang%22:%22zh_CN%22,%22model%22:%22Poke5%22,%22submodel%22:%22%22,%22fingerprint%22:%22%22}
![image](https://github.com/Hagb/decryptBooxUpdateUpx/assets/34123108/e5f99b99-0884-4cd2-a9b0-f3baac33388a)

**Comment by RenateUSB** [comment]
Oh! Thank you. The language is zh_CN:
```
Model:  Poke5
Finger: Onyx/Poke5/Poke5:11/2023-11-17_04-09_3.5_801526b7d/6777:user/dev-keys
Link:   http://firmware-volc.boox.com/44207d5ef900c54aeab756b596c29354/update.upx
Size:   1595705515
MD5:    44207d5ef900c54aeab756b596c29354
```

**Comment by RenateUSB** [comment]
@usb9245 Pasting that as an image is too error-prone. Could you paste that as text or else post /system/lib64/libota_jni.so ? Tnx!

**Comment by Hagb** [comment]
Oh interesting. In the case of Leaf2, `Leaf2_P` is Chinese version and `Leaf2` is international version.

**Comment by usb9245** [comment]
> @usb9245 Pasting that as an image is too error-prone. Could you paste that as text or else post /system/lib64/libota_jni.so ? Tnx!

[libota_jni.zip](https://github.com/Hagb/decryptBooxUpdateUpx/files/13441934/libota_jni.zip)

**Comment by Iey4iej3** [comment]
Close this issue by https://github.com/Hagb/decryptBooxUpdateUpx/commit/d48b8cbc5cbaab4339840462da77ed7657d2357d
