### ISSUE TITLE
ONYX BOOX Note Air 3   BooxKeys.csv  Request BooxKeys.

### ISSUE THREAD

**Issue by sellin82** [Hagb/decryptBooxUpdateUpx#83]
ONYX BOOX Note Air 3 BooxKeys.csv
Request BooxKeys.

Please~

**Comment by RenateUSB** [comment]
Apparently you own a NoteAir3.
I do not own one.
Therefore, to get the keys **you** will have to take some action.

Do you have ADB working on your device? If not, Google it.
`adb pull /system/lib64/libota_jni.so`
Does that exist? Post it.
`adb pull /system/priv-app/OnyxOtaService/OnyxOtaService.apk`

Please do not post more issues on this issue.
