### ISSUE TITLE
ONYX BOOX Tab10 C Request Keys

### ISSUE THREAD

**Issue by crackself** [Hagb/decryptBooxUpdateUpx#91]
Tab10C in China ,please add keys.
[libota_jni.so.zip](https://github.com/Hagb/decryptBooxUpdateUpx/files/14304843/libota_jni.so.zip)
![Screenshot_20240216-082407](https://github.com/Hagb/decryptBooxUpdateUpx/assets/16448332/61961030-fd04-4ea8-865c-a10c5ce99db8)

**Comment by RenateUSB** [comment]
Thanks!
Added Tab10C to BooxKeys.csv
