### ISSUE TITLE
Note Air 3 C: installed version is newer than downloadable version

### ISSUE THREAD

**Issue by tarkeez** [Hagb/decryptBooxUpdateUpx#92]
Installed version is 2023-11-15_15-07_3.5_0a296ec2c (device came with this installed)

But latest available as of now is 2023-10-17_09-55_3.5_a37b266eb

Edit: http://data.onyx-international.cn/api/firmware/update?where={%22buildNumber%22:0,%22buildType%22:%22user%22,%22deviceMAC%22:%22%22,%22lang%22:%22en_US%22,%22model%22:%22NoteAir3C%22,%22submodel%22:%22%22,%22fingerprint%22:%22%22}

Is it because the newer installed version was an incremental update?

I am going to root the device now, is it okay to use boot.img and vbmeta.img from the latest available update.upx , or should I somehow extract it from my device?

Alternatively should I flash the update.upx to downgrade, then root, then update again?

Thanks

Edit: Seeing #42 I tried adding the build fingerprint from my device 
Onyx/NoteAir3C/NoteAir3C:11/2023-11-15_15-07_3.5_0a296ec2c/2880:user/release-keys
still points to the older update.

Does anyone know how to get the newer update (the one I have installed)

**Comment by RenateUSB** [comment]
Since they are both version 3.5 I wouldn't worry too much about incompatibility.
I'd use the boot image from the update.
I don't recall if an EDL loader was found for NoteAir3C, but if it was, then pull the original boot image for backup.

**Comment by tarkeez** [comment]
Thanks for your reply

so using the boot.img and vbmeta.img (this latter image is for disabling verified boot so the system accepts the modded boot image?) from the downloadable update.upx is considered fine because they probably have not modified the boot image on the same major version?

So if another update is launched after this but again not downloadable, just do an device OTA update, lose root (?), and then just repeat the process same patched boot.img if it's a minor update?

btw does the verified boot metadata ever change for the device? Only for major rom updates? Do you have to flash the vbmeta.img every time you flash a patched boot.img?

**Comment by RenateUSB** [comment]
vbmeta changes all the time for any trivial change.
Magisk doesn't verify vbmeta.
Also the flags in vbmeta disable checking.
```
fastboot flash vbmeta myvb.img
 --disable-verity           Sets disable-verity when flashing vbmeta.
 --disable-verification     Sets disable-verification when flashing vbmeta.
```
