### ISSUE TITLE
Provide Firmware Decryption Key for BOOX Tab 8C (Tab Mini C Mainland China Version) 

### ISSUE THREAD

**Issue by HRB-YuPai** [Hagb/decryptBooxUpdateUpx#95]
Model = "Tab8C"
Key = D7731639E43C1C421F25178D79A07031
IV = A419E9D70B549920F91DD28733A51A46

[libota_jni.zip](https://github.com/Hagb/decryptBooxUpdateUpx/files/14968080/libota_jni.zip)

The attachment is the compressed file of libota_jni.so for Tab 8c.

please update the keys csv file.

in appreciation

**Comment by RenateUSB** [comment]
Thanks! Added.
