### ISSUE TITLE
Provide libota_jni.so for BOOX NoteX3S(Mainland China Version)

### ISSUE THREAD

**Issue by LeeDespo** [Hagb/decryptBooxUpdateUpx#99]
model:NoteX3S
I try to decrypt the key accessed by JNI method,but fail. Terminal prompt that it cannot import name 'emu_const' from 'androidemu.const'. I can not solve it.I hope there are kind-heart people who can solve it, thank you very mach.
[libota_jni.zip](https://github.com/user-attachments/files/15513398/libota_jni.zip)
The upx file:http://firmware.boox.com/508e7c1042770bcea926ed88dc840cef/update.upx

**Comment by RenateUSB** [comment]
Added to BooxKeys.csv
